import Head from "next/head";
import Image from "next/image";
import { Inter } from "next/font/google";
import styles from "@/styles/Home.module.css";
import Link from "next/link";
import ProductList from "./component/ProductList";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
        <link
          rel="stylesheet"
          href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.1.1/css/all.min.css"
          integrity="sha512-KfkfwYDsLkIlwQp6LFnl8zNdLGxu9YAA1QvwINks4PhcElQSvqcyVLLD9aMhXd13uQjoXtEKNosOWaZqXgel0g=="
          crossOrigin="anonymous"
          referrerPolicy="no-referrer"
        />
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link rel="preconnect" href="https://fonts.gstatic.com" />
        <link
          href="https://fonts.googleapis.com/css2?family=Inter:wght@400;600;700&display=swap"
          rel="stylesheet"
        />
      </Head>

      <main>
        <main className="py-16">
          <div className="productWrapper">
            <ProductList />
            <div>
              {/* <!-- Product Input Form --> */}
              <div className="formContainer">
                <h4 className="formTitle">Add New Product</h4>
                <form
                  className="space-y-4 text-[#534F4F]"
                  id="lws-addProductForm"
                >
                  {/* <!-- product name --> */}
                  <div className="space-y-2">
                    <label htmlFor="lws-inputName">Product Name</label>
                    <input
                      className="addProductInput"
                      id="lws-inputName"
                      type="text"
                      required
                    />
                  </div>
                  {/* <!-- product category --> */}
                  <div className="space-y-2">
                    <label htmlFor="lws-inputCategory">Category</label>
                    <input
                      className="addProductInput"
                      id="lws-inputCategory"
                      type="text"
                      required
                    />
                  </div>
                  {/* <!-- product image url --> */}
                  <div className="space-y-2">
                    <label htmlFor="lws-inputImage">Image Url</label>
                    <input
                      className="addProductInput"
                      id="lws-inputImage"
                      type="text"
                      required
                    />
                  </div>
                  {/* <!-- price & quantity container --> */}
                  <div className="grid grid-cols-2 gap-8 pb-4">
                    {/* <!-- price --> */}
                    <div className="space-y-2">
                      <label htmlFor="ws-inputPrice">Price</label>
                      <input
                        className="addProductInput"
                        type="number"
                        id="lws-inputPrice"
                        required
                      />
                    </div>
                    {/* <!-- quantity --> */}
                    <div className="space-y-2">
                      <label htmlFor="lws-inputQuantity">Quantity</label>
                      <input
                        className="addProductInput"
                        type="number"
                        id="lws-inputQuantity"
                        required
                      />
                    </div>
                  </div>
                  {/* <!-- submit button --> */}
                  <button type="submit" id="lws-inputSubmit" className="submit">
                    Add Product
                  </button>
                </form>
              </div>
              {/* <!-- Product Input Form Ends --> */}
            </div>
          </div>
        </main>
      </main>
    </>
  );
}
